export type CareerGuide = {
  introduction: string;
  work: string;
  training: string;
  fit: string;
  terms: [string, string][];
  tryIt: string;
  ask: string;
  sources: [string, string][];
};

const faaPilot: [string, string] = ["FAA: becoming a pilot", "https://www.faa.gov/pilots/become"];
const blsPilot: [string, string] = ["BLS: airline and commercial pilots", "https://www.bls.gov/ooh/transportation-and-material-moving/airline-and-commercial-pilots.htm"];
const maintenance: [string, string] = ["BLS: aircraft mechanics and avionics technicians", "https://www.bls.gov/ooh/installation-maintenance-and-repair/aircraft-and-avionics-equipment-mechanics-and-technicians.htm"];
const nasa: [string, string] = ["NASA: careers", "https://www.nasa.gov/careers/"];
const nba: [string, string] = ["NBAA: professional development", "https://nbaa.org/professional-development/"];

// Career scope draws on Cleared for Takeoff, “Careers in the Aviation Industry,”
// pp. 32–42. Requirements use the linked official sources, reviewed 2026-09-13.
// Activities and questions are Gateway's suggested exploration exercises.
export const careerGuides: Record<string, CareerGuide> = {
  "professional-pilot-careers": {
    introduction: "A professional pilot is paid to fly, but the job starts well before takeoff. Pilots prepare the aircraft and the plan, work with other people, and decide whether a flight should go ahead. Airlines are one option among many: teaching, business travel, cargo, public service, and specialist missions all need pilots.",
    work: "A working day can include checking the aircraft, reviewing the route, talking with the crew, flying, and recording any problems after landing. An important part of the job is changing a plan when conditions change. Good judgment matters as much as confident aircraft handling.",
    training: "Choose the type of aircraft and work that interests you, then compare training routes. Certificates show what flying you may do; ratings add privileges for particular aircraft or conditions. Ask a school to map the stages from beginner training to your intended job, including experience, medical requirements, and tests.",
    fit: "This could suit you if you enjoy preparation, teamwork, and taking responsibility. Training takes sustained time and money, and work schedules differ widely. Compare the lifestyle of several pilot jobs before choosing a school.",
    terms: [["Certificate", "An FAA qualification that describes a pilot's privileges."], ["Rating", "An additional qualification, such as permission to fly using instruments in specified conditions."]],
    tryIt: "Compare two nearby schools. Request an itemized estimate covering aircraft rental, instruction, supplies, tests, and extra practice. An airport open house is a useful free first step.",
    ask: "What did your actual training cost, and what would you do differently as a beginner?",
    sources: [faaPilot, blsPilot],
  },
  "airline-pilot": {
    introduction: "Airline pilots carry passengers or freight on scheduled routes. The captain and first officer work as a team, sharing flying and monitoring duties. Both need to speak up, notice problems, and make careful decisions.",
    work: "Picture a departure delayed by weather: the crew reviews the updated plan, coordinates with dispatch, and keeps safety ahead of the timetable. Flying is only part of the work; briefings, checklists, and recurring training are part of the profession too.",
    training: "The route usually involves earlier pilot certificates, substantial flight experience, and airline transport pilot qualifications. A commercial certificate alone does not make someone ready for an airline job. Check each employer's current requirements and compare college and independent flight-school routes.",
    fit: "You may enjoy this if you like structured teamwork and learning complex systems. Nights away, changing schedules, and the location of your assigned base affect daily life. Regional flying does not automatically mean being home every night.",
    terms: [["ATP", "Airline Transport Pilot: an advanced pilot certificate."], ["First officer", "The other qualified pilot working alongside the captain; often called the copilot."]],
    tryIt: "Read two airline pilot job postings and make separate lists of required qualifications and preferred qualifications. Mark the steps you would need to reach each.",
    ask: "How do your base, schedule, and time away from home affect your week?",
    sources: [blsPilot, faaPilot],
  },
  "corporate-charter-and-air-taxi-pilot": {
    introduction: "These pilots take people where they need to go on trips arranged around the customer. A company may employ its own crew, while a charter business sells flights to different clients. Aircraft and destinations can vary considerably.",
    work: "Beyond flying, a small team may coordinate the trip, check destination arrangements, and respond to schedule changes. Professional service means explaining limitations clearly as well as helping passengers. A requested departure time still has to fit a safe plan.",
    training: "Start with the pilot qualifications appropriate to the aircraft and operation. Employers may require additional experience and aircraft-specific training. Compare actual vacancies: there is no single qualification package that fits every business aircraft job.",
    fit: "This may suit someone who enjoys variety, responsibility, and working closely with customers. Ask about on-call duties, time away, and how much trip planning the crew handles.",
    terms: [["Charter", "A flight arranged for a particular customer rather than a regular public schedule."], ["Flight department", "The people who organize and operate a company's aircraft."]],
    tryIt: "Explore NBAA's career resources and compare a company pilot role with a charter role. Note which responsibilities happen on the ground.",
    ask: "How much notice do you receive before a trip, and who handles the planning?",
    sources: [nba, faaPilot],
  },
  "cargo-and-ferry-pilot": {
    introduction: "Cargo pilots move goods. Ferry pilots move the aircraft itself, such as delivering it to a new owner or taking it to another operating location. These are related but different jobs, with different customers and trip patterns.",
    work: "A cargo mission centers on getting a shipment to its destination. A ferry assignment centers on understanding the aircraft and arranging its delivery. In either case, unfamiliar airports or changed plans can make preparation especially valuable.",
    training: "Build the certificates, aircraft experience, and operational knowledge required for the specific employer. Large cargo airlines and small operators do not all hire at the same experience level. Do not assume ferry work is an easy first job simply because there are no passengers.",
    fit: "This could fit someone who enjoys logistics and independent preparation. Discuss night work, trip length, support away from base, and how crews manage fatigue.",
    terms: [["Ferry flight", "A flight made to reposition or deliver an aircraft."], ["Logistics", "Organizing how goods or equipment move from one place to another."]],
    tryIt: "Choose a package-delivery company and an aircraft-delivery business. Compare their pilot vacancies and the types of aircraft they use.",
    ask: "What makes preparing for a delivery flight different from your usual flying?",
    sources: [blsPilot, faaPilot],
  },
  "medical-and-air-ambulance-pilot": {
    introduction: "Medical pilots transport patients, medical teams, or organs. Some flights respond to emergencies; others transfer patients between facilities. Helicopters and airplanes serve different missions. The pilot's responsibility is the flight, while trained medical crew members provide care.",
    work: "A mission can require close coordination among flight crew, medical staff, and people at the destination. The urgency of a patient's needs makes a disciplined decision process especially important. A safe crew must be able to delay or decline a flight.",
    training: "Develop the qualifications and experience required by the particular medical operator. This is a specialist destination to work toward, rather than a qualification gained through an introductory flight course. Compare helicopter and airplane pathways before committing to training.",
    fit: "You may value the direct public-service purpose. Also ask about shifts, standby time, difficult situations, and the support available to crews.",
    terms: [["Air ambulance", "An aircraft equipped and staffed to transport patients."], ["Crew coordination", "Sharing information and responsibilities so the whole team can make sound decisions."]],
    tryIt: "Look for a medical operator's public career presentation or open house. Write down which qualifications belong to pilots and which belong to clinicians.",
    ask: "How does your team protect a pilot's ability to say no when a mission cannot be flown safely?",
    sources: [faaPilot, ["Association of Air Medical Services", "https://aams.org/"]],
  },
  "government-military-and-law-enforcement-pilot": {
    introduction: "Public-service pilots support missions such as transport, patrol, rescue, research, and defense. Civilian agency employment, police aviation, and military service are separate routes. They should be compared individually rather than treated as one career ladder.",
    work: "The mission shapes the work: transporting a team is different from observing an area or supporting a rescue. Pilots coordinate with the people using the aircraft, while remaining responsible for sound flying decisions.",
    training: "Read the actual agency or service recruitment information. Some jobs recruit experienced civilian pilots; military routes have their own selection, training, and service obligations. Eligibility, medical standards, and background requirements depend on the role.",
    fit: "This may appeal if service and teamwork motivate you. Consider the wider job, including location, deployment or transfer expectations, and commitments beyond flight training.",
    terms: [["Mission", "The particular task the crew is carrying out."], ["Civilian pilot", "A pilot working outside a military role, including for a government agency."]],
    tryIt: "Compare one civilian government pilot vacancy with one military pilot recruiting page. List qualifications, obligations, and unanswered questions separately.",
    ask: "What duties and commitments come with this role besides flying?",
    sources: [faaPilot, ["FAA: aviation careers", "https://www.faa.gov/jobs/career_fields/aviation_careers"]],
  },
  "firefighting-and-agricultural-pilot": {
    introduction: "Firefighting pilots support wildfire response, while agricultural pilots help treat crops or land from the air. Both involve specialized missions, but the training, equipment, and employers differ. They are experienced-pilot pathways to explore carefully.",
    work: "An agricultural crew needs to understand the treatment area, weather, and application plan. Fire aviation involves coordination with the wider response team. Ground preparation and disciplined teamwork are central to both kinds of work.",
    training: "Build a strong flying foundation before specialist training. Agricultural aviation adds knowledge about application work and its operating requirements; fire operators have mission-specific qualifications. An ordinary commercial certificate is only part of preparation.",
    fit: "This may interest people who enjoy practical work and outdoor industries. Seasonality and demanding conditions matter. Learn from established operators rather than trying to imitate specialist flying on your own.",
    terms: [["Aerial application", "Applying materials to crops or land using an aircraft."], ["Retardant", "A material used in some wildfire operations to slow the spread of fire."]],
    tryIt: "Read NAAA's career introduction and look for a public fire-aviation career event. Compare the ground-support jobs that help each operation succeed.",
    ask: "What experience should a beginner build before applying for specialist training?",
    sources: [["NAAA: agricultural aviation careers", "https://www.agaviation.org/career/"], ["U.S. Forest Service: fire careers", "https://www.fs.usda.gov/working-with-us/careers/fire"]],
  },
  "air-tour-media-and-banner-pilot": {
    introduction: "Some pilots help visitors see a region, carry a camera team, or tow an advertising banner. These jobs connect flying with tourism, storytelling, and local business. Each mission has its own skills and operating requirements.",
    work: "A tour pilot considers the passenger experience; a media pilot coordinates with the people recording a story; a banner pilot performs a specialized towing task. In every case, the customer's goal must fit a safe flight.",
    training: "Compare the qualifications and mission training required by real operators. Paid flying requires appropriate pilot privileges, and each kind of operation may have additional rules. A new certificate does not automatically qualify you for every advertised flying job.",
    fit: "You may like local knowledge, communication, and varied assignments. Ask whether work is seasonal and what happens when weather cancels a day's schedule.",
    terms: [["Air tour", "A sightseeing flight."], ["Banner towing", "Flying with an advertising banner attached using specialized equipment and procedures."]],
    tryIt: "Choose one tour or aerial-media operator and research its aircraft, customers, and pilot requirements. Make a list of skills beyond aircraft handling.",
    ask: "How do you balance a customer's request with weather and operational limits?",
    sources: [faaPilot, blsPilot],
  },
  "test-airshow-and-space-pilot": {
    introduction: "Test flying, airshow performance, and human spaceflight are three distinct specialisms. Test pilots help evaluate aircraft; airshow pilots demonstrate carefully prepared flying; astronaut crews train for space missions. Interest in one does not require following all three.",
    work: "Test flying involves disciplined observation and reporting. Airshow work involves preparation for a planned demonstration. Space crews spend extensive time training and working with teams on Earth. The visible flight is only one part of each role.",
    training: "These paths require substantial preparation specific to the job. NASA's astronaut route includes education, professional experience, and selection requirements; being a pilot is not the only way to qualify. Consult the current NASA criteria rather than assuming all astronauts come from test flying.",
    fit: "This could appeal if you enjoy meticulous practice and learning from evidence. Consider related engineering and research roles too; they let you contribute to the same missions.",
    terms: [["Flight test", "A planned evaluation of how an aircraft or system behaves."], ["Aerobatics", "Specialized flight maneuvers requiring appropriate training and aircraft."]],
    tryIt: "Read the biographies of a NASA scientist-astronaut and a pilot-astronaut. Compare the skills and experiences they developed before selection.",
    ask: "What work happens between flights, and which skills make someone useful to the team?",
    sources: [["NASA: becoming an astronaut", "https://www.nasa.gov/humans-in-space/astronauts/become-an-astronaut/"], faaPilot],
  },
  "flight-instructor": {
    introduction: "A flight instructor helps someone become a safe, thoughtful pilot. That means explaining ideas, demonstrating skills, spotting misunderstandings, and giving feedback. Teaching well is a skill of its own, even for a very capable pilot.",
    work: "A lesson might begin with a discussion, move into practice in an aircraft or simulator, and finish with a review. Instructors adapt to different learners and decide when a student is ready for another stage of training.",
    training: "You first develop your own flying qualifications, then complete the instructor preparation appropriate to what you want to teach. Ask a flight school to explain the certificates and ratings involved, including the separate preparation for teaching instrument flying.",
    fit: "Patience, clear explanations, and honest feedback matter. Some people make instruction their long-term career; others combine it with other flying. Either way, the student's learning needs deserve your full attention.",
    terms: [["CFI", "Certified Flight Instructor."], ["Debrief", "A discussion after a lesson about what went well and what to practice next."]],
    tryIt: "Teach a friend a simple skill and ask which explanation helped most. At a flying club, ask whether you can observe a ground lesson with permission.",
    ask: "How do you adapt a lesson when a student is trying hard but not understanding?",
    sources: [faaPilot],
  },
  "drone-pilot": {
    introduction: "Drone pilots collect images or other information from the air for tasks such as mapping, inspections, and photography. The useful result might be a roof inspection or a map, so understanding the customer's problem matters alongside flying.",
    work: "A project can involve planning the site visit, checking operating restrictions, collecting useful material, and organizing the results. Learning photography, mapping software, or data handling can help you turn a flight into something valuable.",
    training: "For the U.S. Part 107 route, the FAA requires remote pilots to be at least 16. First-time applicants take the knowledge exam at an approved testing center. Eligible existing pilots have a separate training route. Certificate holders also complete recurrent training to maintain knowledge currency.",
    fit: "This may suit someone who enjoys technology and project work. Having a certificate does not authorize every flight: the location, aircraft, and proposed operation still matter.",
    terms: [["Part 107", "The FAA rules used for many small-drone operations."], ["Remote pilot", "The person responsible for flying a drone from the ground."]],
    tryIt: "Use the FAA's free study resources before buying equipment. Create a mock project brief explaining what information a customer needs and how you would present it.",
    ask: "Which skill earns you work beyond simply being able to fly the drone?",
    sources: [["FAA: becoming a certificated remote pilot", "https://www.faa.gov/uas/commercial_operators/become_a_drone_pilot"]],
  },
  "air-traffic-control": {
    introduction: "Air traffic controllers help aircraft move safely through shared airspace and around airports. They build a picture of where aircraft are and where they are going, then communicate clear instructions to pilots.",
    work: "Controllers work in different settings, including towers and facilities managing traffic between airports. A busy period calls for concentration, short precise messages, and coordination with other controllers. The job is about organized decisions, not simply talking quickly.",
    training: "The FAA has a specific hiring and training process. Entry routes and eligibility vary, so use the current hiring announcement to check education or experience, assessments, and other conditions. Training continues at the assigned facility after initial preparation.",
    fit: "This could suit someone who likes focused teamwork and making decisions with changing information. Shift patterns and the responsibility of the role are important parts of the career to discuss.",
    terms: [["Separation", "The required space or time maintained between aircraft."], ["Handoff", "Transferring responsibility for an aircraft to another controller."]],
    tryIt: "Read the FAA's controller hiring guide and write a timeline of its stages. Practice summarizing a complicated situation in two clear sentences.",
    ask: "What was most challenging about learning to work at your first facility?",
    sources: [["FAA: air traffic controller hiring", "https://www.faa.gov/atc-hiring"]],
  },
  "airport-operations": {
    introduction: "Airport operations staff help keep the airfield ready for use. They connect the work of maintenance teams, airlines, emergency responders, and other airport users. Much of their contribution happens behind the scenes.",
    work: "A day may include inspecting pavement and signs, reporting a problem, or coordinating activity around construction or bad weather. For example, a damaged light becomes a task to record, communicate, and follow through until it is addressed.",
    training: "Compare airport job postings for the education, experience, and local training they request. Aviation management study can help, but requirements differ by role. Learning how an airport works and developing clear reporting habits are useful foundations.",
    fit: "You may enjoy this if you like practical problem-solving and coordinating people. Some duties are outdoors, and airport schedules can include nights and weekends.",
    terms: [["Airfield", "The airport areas used for aircraft movement, such as runways and taxiways."], ["Taxiway", "A route aircraft use to move on the ground between airport areas."]],
    tryIt: "Study a public airport map. Identify runways, taxiways, and terminals, then list which teams would need to communicate during a runway repair.",
    ask: "What does an entry-level operations employee learn in the first three months?",
    sources: [["FAA: airport safety", "https://www.faa.gov/airports/airport_safety"]],
  },
  "flight-dispatch": {
    introduction: "Dispatchers help flights operate safely from the ground. They work with flight crews to assess routes, weather, fuel, and changing conditions. It is a way to be closely involved in flying without working in the cockpit.",
    work: "Imagine weather developing along a planned route. A dispatcher gathers the relevant information, considers alternatives, and communicates with the crew. The job continues after departure as the team monitors the flight and responds to changes.",
    training: "For the U.S. aircraft dispatcher certificate route, explore FAA-approved Part 65 courses and current certification requirements. Ask each program about eligibility, instruction, testing, and total cost. Dispatcher training is distinct from pilot training.",
    fit: "This may suit someone who likes maps, weather, analysis, and clear communication. Operations centers work around flight schedules, so ask about shifts and workload.",
    terms: [["Dispatch", "Planning and monitoring flights from the ground."], ["Alternate airport", "Another airport included in planning in case the intended destination cannot be used."]],
    tryIt: "Compare two FAA-listed dispatcher programs. Ask what a sample lesson looks like and which costs are included in the advertised fee.",
    ask: "What does a dispatcher do when the original flight plan stops being the best option?",
    sources: [["FAA: approved dispatcher courses", "https://www.faa.gov/about/office_org/headquarters_offices/avs/part-65-aircraft-dispatcher-certification-courses"]],
  },
  "aircraft-maintenance": {
    introduction: "Aircraft mechanics keep aircraft fit for service through inspection, maintenance, and repair. If you enjoy understanding how things work and checking your work carefully, this is a hands-on way to contribute to aviation safety.",
    work: "A mechanic may investigate a reported fault, consult maintenance instructions, perform the work, and document it. Finding the reason for a problem is as important as replacing a part. Accurate records help the next person understand what was done.",
    training: "The FAA describes approved-school and practical-experience routes to mechanic certification. A&P means airframe and powerplant, covering the aircraft structure and its engines. Compare programs' tools, tuition, practical training, and testing costs before enrolling.",
    fit: "This can suit patient, detail-oriented learners who like physical work. Work may involve noise, awkward spaces, and shifts. Being willing to ask questions and follow instructions precisely is a strength.",
    terms: [["A&P", "Airframe and Powerplant: the two FAA mechanic ratings commonly held together."], ["Troubleshooting", "Working through possible causes to find why something is not working."]],
    tryIt: "Visit a maintenance school's open day. Ask to see a typical practical exercise and learn what tools a student must buy.",
    ask: "How do you check and document a repair before the aircraft returns to service?",
    sources: [["FAA: becoming an aviation mechanic", "https://www.faa.gov/mechanics/become"], maintenance],
  },
  "avionics-technician": {
    introduction: "Avionics means the electronic equipment used in aircraft. Technicians work with systems that help crews communicate, navigate, and understand what the aircraft is doing. This career connects electronics with practical investigation.",
    work: "A fault may require checking wiring, reading diagrams, using test equipment, and determining whether the problem is in a component or its connections. Careful testing and records matter because another person must be able to understand the work.",
    training: "Explore electronics and aviation technical programs, then compare their preparation with employer requirements. Qualifications depend on the duties; avionics work is not identical to the full A&P mechanic pathway. Ask programs exactly which credentials they prepare you for.",
    fit: "This may suit you if you enjoy circuits, systematic problem-solving, and precise work. Patience is useful when a problem appears only occasionally.",
    terms: [["Avionics", "Aircraft electronics, including communication and navigation equipment."], ["Schematic", "A diagram showing how an electrical circuit is connected."]],
    tryIt: "Build a simple low-voltage classroom circuit or use a circuit simulator. Document a fault and the checks you used to find it; do not experiment on aircraft equipment.",
    ask: "Which electronics skills and qualifications do you look for in a new technician?",
    sources: [maintenance],
  },
  "aeronautical-engineering": {
    introduction: "Aeronautical engineers help design and improve aircraft. Aerospace engineering also includes spacecraft. Teams work on different parts of a design, such as structures, propulsion, controls, or how air moves around a wing.",
    work: "An engineer might compare designs using calculations or computer models, review test results, and explain a proposed change. Design involves tradeoffs: making a part lighter, for example, must be balanced with how it performs and how it can be made.",
    training: "An engineering bachelor's degree is the usual starting point. Compare aerospace programs with related fields such as mechanical and electrical engineering. Projects and internships help connect classroom mathematics and physics with real design decisions.",
    fit: "This may suit someone who enjoys asking why, testing ideas, and revising a solution. Communication matters because engineers rarely design a complete aircraft alone.",
    terms: [["Aerodynamics", "How air moves around objects and affects them."], ["Propulsion", "The system that produces the force to move an aircraft or spacecraft."]],
    tryIt: "Design two paper gliders, change one feature, and record several test flights. Explain the limits of your experiment as well as the result.",
    ask: "What does a new engineer actually work on, and how are their designs reviewed?",
    sources: [["BLS: aerospace engineers", "https://www.bls.gov/ooh/architecture-and-engineering/aerospace-engineers.htm"]],
  },
  "meteorology": {
    introduction: "Meteorologists study the atmosphere and explain what the weather is likely to do. In aviation, their work helps people understand conditions that affect flights. The skill is both scientific analysis and communicating uncertainty clearly.",
    work: "A forecaster compares observations with model predictions and updates the picture as new information arrives. For aviation, the useful question might be when visibility will improve or where thunderstorms may develop.",
    training: "Atmospheric science or a related science degree is a common route. Mathematics, physics, and computing help you work with weather data. Research roles may involve further study. Learning aviation weather language adds context to the science.",
    fit: "This could fit someone who likes patterns, data, and explaining complex ideas. A forecast is not a promise; being honest about uncertainty is part of doing the job well.",
    terms: [["Weather model", "A computer calculation of how atmospheric conditions may change."], ["Visibility", "How far someone can see clearly in the prevailing conditions."]],
    tryIt: "Keep a week-long weather journal comparing a forecast with what happened. Note which predictions were useful and where timing or location differed.",
    ask: "How do you explain a forecast when several different outcomes are possible?",
    sources: [["BLS: atmospheric scientists and meteorologists", "https://www.bls.gov/ooh/life-physical-and-social-science/atmospheric-scientists-including-meteorologists.htm"]],
  },
  "cabin-crew-and-customer-experience": {
    introduction: "Flight attendants help keep passengers safe and supported in the cabin. Service is visible, but safety preparation, communication, and responding to unexpected situations are central responsibilities.",
    work: "A crew prepares before boarding, checks the cabin, briefs passengers, and stays alert during the flight. They may need to calm a worried traveler, manage a disagreement, or respond to a medical event as a team.",
    training: "Airlines select and train their cabin crews. Review the actual employer's entry requirements before paying for outside courses. Customer-service experience and strong communication can help you prepare; airline training covers the role's specific procedures.",
    fit: "You may enjoy helping people and working with changing teams. Consider physical demands, irregular hours, and time away from home as well as travel opportunities.",
    terms: [["Cabin crew", "The team responsible for passenger safety and service in the aircraft cabin."], ["Recurrent training", "Training repeated during a career to maintain knowledge and skills."]],
    tryIt: "Build experience helping people through a school event, volunteer role, or service job. Practice calmly explaining a change of plan to someone who is frustrated.",
    ask: "What surprised you about the safety responsibilities when you began training?",
    sources: [["BLS: flight attendants", "https://www.bls.gov/ooh/transportation-and-material-moving/flight-attendants.htm"]],
  },
  "airport-customer-service": {
    introduction: "Airport customer-service agents help travelers move through the airport. They may work at check-in, gates, or service desks, helping with boarding, baggage questions, and changes to journeys.",
    work: "A delay can turn a routine shift into a problem-solving exercise. An agent checks available options, explains them clearly, and coordinates with colleagues. Helping someone understand what happens next can make a difficult journey more manageable.",
    training: "Look at airline and ground-service company vacancies for entry requirements and employer training. Practice communication, computer skills, and handling competing requests. These roles are different from flight-attendant jobs, even when the employer is the same airline.",
    fit: "This may suit someone who likes direct contact with people and practical decisions. Busy queues, standing, and early or late shifts are useful topics to ask about.",
    terms: [["Gate agent", "An employee who helps manage passengers and boarding at the departure gate."], ["Rebooking", "Changing a traveler's reservation to another flight."]],
    tryIt: "Create a sample message explaining a delayed school trip. Include what is known, what happens next, and where people can get help.",
    ask: "What training helps a new agent handle disruptions and accessibility requests?",
    sources: [["BLS: customer service representatives", "https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm"]],
  },
  "airport-emergency-response": {
    introduction: "Airport emergency teams prepare for incidents involving aircraft and the people around them. Aircraft rescue and firefighting is a specialist part of emergency services, connecting firefighting skills with knowledge of the airport environment.",
    work: "Preparation includes training exercises, equipment checks, and coordination with other responders. The work is not constant emergency action: readiness depends on routine practice and understanding how teams will communicate.",
    training: "Check the hiring and qualification requirements of the airport or fire department. General fire-service preparation and airport-specific training are different parts of the route. Medical qualifications may depend on the position.",
    fit: "This may appeal if you value service, practical teamwork, and disciplined preparation. Ask about physical demands, shifts, and support after difficult incidents.",
    terms: [["ARFF", "Aircraft Rescue and Fire Fighting."], ["Emergency exercise", "A practice scenario used to test how responders and organizations work together."]],
    tryIt: "Ask a local fire department about a public open house or age-appropriate career program. Learn how airport response differs from other firefighting.",
    ask: "Which qualifications should someone obtain before applying, and which are taught after hiring?",
    sources: [["FAA: aircraft rescue and firefighting", "https://www.faa.gov/airports/airport_safety/aircraft_rescue_fire_fighting"]],
  },
  "airport-police-and-security": {
    introduction: "Several different teams protect an airport. Screening officers check travelers and belongings; airport police perform law-enforcement duties; other security staff may manage access. These jobs have different authority and hiring pathways.",
    work: "The work can involve explaining procedures, observing carefully, responding to a concern, and coordinating with colleagues. Respectful communication is important in a setting where travelers may be stressed or unfamiliar with the process.",
    training: "Compare a TSA screening role with a local airport police vacancy. Police positions follow the relevant agency's law-enforcement requirements; TSA has its own recruitment and training process. Do not assume one automatically qualifies you for the other.",
    fit: "This may suit someone who values public service, consistency, and calm communication. Review the actual position's screening process, hours, and responsibilities.",
    terms: [["TSO", "Transportation Security Officer, a TSA screening role."], ["Access control", "Checking who is authorized to enter a particular area."]],
    tryIt: "Make a side-by-side comparison of two public job announcements: employer, duties, training, and entry requirements.",
    ask: "How does this team's role differ from the other security teams at the airport?",
    sources: [["TSA: career paths", "https://jobs.tsa.gov/careers-at-tsa"]],
  },
  "aviation-training-and-education": {
    introduction: "Aviation educators help people learn the knowledge and habits needed for their work. Some teach in classrooms, some create learning materials, and others train people on equipment or in simulators.",
    work: "An educator turns a complicated task into understandable steps, creates practice opportunities, and checks whether learners can apply what they learned. Updating a lesson after feedback is part of the work.",
    training: "The route depends on the subject and setting. Teaching aircraft maintenance, school science, or flight procedures involves different qualifications. Build subject knowledge and teaching experience, then compare the requirements of the institutions that interest you.",
    fit: "This may suit you if you enjoy helping someone reach an understanding. Being knowledgeable helps, but listening and adapting an explanation are just as important.",
    terms: [["Curriculum", "The organized plan of what a course teaches."], ["Assessment", "A way to check what a learner understands or can do."]],
    tryIt: "Create a five-minute lesson about a simple aviation idea. Ask your learner to explain it back, then revise the part that was unclear.",
    ask: "How do you know whether a student can apply a lesson outside the classroom?",
    sources: [["FAA: training and schools", "https://www.faa.gov/training_testing/schools"]],
  },
  "aerospace-medicine": {
    introduction: "Aerospace medicine studies how flight and space environments affect people's health and performance. The wider field includes clinicians and researchers. An Aviation Medical Examiner is a physician authorized by the FAA to conduct specified pilot medical examinations.",
    work: "Depending on the role, work may involve medical examinations, research, or helping an organization understand human performance. Caring for a patient during transport and examining a pilot for certification are different jobs with different preparation.",
    training: "Physician roles require medical education and professional licensing, followed by the relevant specialist preparation or designation. Research and other health-profession roles have their own routes. Start by identifying which activity interests you, rather than treating aerospace medicine as one qualification.",
    fit: "This may appeal if biology, people, and aviation all interest you. Expect careful study, ethical responsibility, and collaboration across professions.",
    terms: [["AME", "Aviation Medical Examiner: an FAA-designated physician."], ["Human performance", "How people function while carrying out tasks, including the effects of fatigue and their environment."]],
    tryIt: "Compare the work of an AME with that of an aerospace researcher. Explore a biology project or a suitable health-care careers event.",
    ask: "Which professional qualification comes first for the work you do, and how did aviation become your specialty?",
    sources: [["FAA: Aviation Medical Examiner guide", "https://www.faa.gov/ame_guide"]],
  },
  "aviation-law-and-business": {
    introduction: "Aviation needs people who understand contracts, organizations, money, and public policy. A lawyer may advise on legal questions, while a business professional may work on planning, finance, or management. These are connected fields with distinct entry routes.",
    work: "A legal task might involve researching a rule or reviewing an agreement. A business task might involve comparing costs or organizing a service. In both, clear writing and understanding the aviation context help turn information into a useful decision.",
    training: "Legal practice requires the relevant legal education and licensing. Business careers can begin through several degree and experience routes. Choose the kind of work first, then investigate aviation-focused internships or projects within that profession.",
    fit: "This could suit someone who enjoys reading, writing, negotiation, and careful analysis. You can contribute to aviation through these skills without becoming a pilot.",
    terms: [["Compliance", "Meeting the rules that apply to an activity."], ["Contract", "An agreement setting out the parties' rights and responsibilities."]],
    tryIt: "Read an airport's public annual report. Pick one business decision and write down the financial, customer, and legal questions you would ask.",
    ask: "Which skills from your original profession helped most when you moved into aviation?",
    sources: [["FAA: Office of the Chief Counsel", "https://www.faa.gov/about/office_org/headquarters_offices/agc"], nba],
  },
  "aviation-insurance-and-risk": {
    introduction: "Insurance and risk professionals help aviation organizations understand what could go wrong and how financial losses may be covered. Underwriters, brokers, claims staff, and lawyers do different parts of this work.",
    work: "An underwriter evaluates information when deciding on coverage. Claims work looks at a reported loss and the policy involved. Risk work asks how problems might be prevented or reduced. The common thread is careful analysis and clear explanation.",
    training: "Business, finance, analytical, and communication skills can support entry into insurance. Licensing and training depend on the role and location. An insurance lawyer needs legal qualifications; not everyone working in aviation insurance is a lawyer.",
    fit: "This may suit someone who likes asking detailed questions and explaining decisions fairly. Interest in aircraft helps, but the job also involves documents, numbers, and relationships.",
    terms: [["Underwriting", "Evaluating a risk to decide whether and on what terms to insure it."], ["Claim", "A request for an insurer to cover a loss under a policy."]],
    tryIt: "Create a fictional flying-club profile and list the questions an insurer might ask. Focus on understanding the business rather than choosing actual insurance.",
    ask: "What distinguishes an entry-level insurance role from a legal or specialist risk role?",
    sources: [["BLS: insurance underwriters", "https://www.bls.gov/ooh/business-and-financial/insurance-underwriters.htm"]],
  },
  "airport-engineering-and-construction": {
    introduction: "Airport engineers help turn plans for runways, drainage, lighting, and buildings into infrastructure people can use. Construction teams then help build or improve it. The work connects civil engineering with the needs of an operating airport.",
    work: "A project may involve surveys, drawings, cost estimates, and coordinating construction stages. Airport work also requires thinking about how people and aircraft will keep moving while part of the site is being changed.",
    training: "Civil engineering commonly begins with an engineering degree; construction management and skilled trades offer other ways into airport projects. Professional licensing depends on the work and jurisdiction. Compare these routes rather than assuming everyone on a project is an engineer.",
    fit: "This may suit people who like practical design and seeing a project become real. Work can combine office analysis, meetings, and site visits.",
    terms: [["Infrastructure", "The physical systems a place needs to operate."], ["Drainage", "The way water is collected and carried away from surfaces."]],
    tryIt: "Sketch a model airport and consider where rainwater would go. Explain how a construction area could affect nearby paths and services.",
    ask: "How do you plan construction while keeping the rest of an airport operating?",
    sources: [["FAA: airport engineering and construction", "https://www.faa.gov/airports/engineering"], ["BLS: civil engineers", "https://www.bls.gov/ooh/architecture-and-engineering/civil-engineers.htm"]],
  },
  "space-science-and-astronautics": {
    introduction: "Space careers include studying planets, designing spacecraft, writing software, and supporting missions from Earth. Astronautics is the engineering of spaceflight. You can work on space missions without becoming an astronaut.",
    work: "A scientist might analyze measurements to answer a research question. An engineer might test a component, and a mission team might plan how to use an instrument. These contributions depend on people explaining their work across specialties.",
    training: "Choose the discipline behind the task: physics, computing, engineering, or another relevant field. Research positions may require graduate study, while other roles have different entry routes. NASA's career and student resources show the range of professions involved.",
    fit: "This may appeal if you enjoy difficult questions and long-term teamwork. Progress often involves repeated tests and revisions rather than a single dramatic launch.",
    terms: [["Astronautics", "The science and engineering of spaceflight."], ["Mission operations", "The work of planning and supporting what a spacecraft does during a mission."]],
    tryIt: "Explore a NASA mission and identify three people or teams behind it. Choose a small coding, design, or science project related to one of their tasks.",
    ask: "Which subject should a student explore first to try the kind of work your team does?",
    sources: [nasa, ["NASA: astronaut requirements", "https://www.nasa.gov/humans-in-space/astronauts/become-an-astronaut/"]],
  },
};
