export const careerPaths = [
  ["plane", "Professional Pilot Careers", "Explore airlines, regional carriers, corporate aviation, cargo, charter, medical transport, government service, firefighting, agriculture, air tours, test piloting, and spaceflight."],
  ["code", "Drone Pilot", "Use uncrewed aircraft for photography, inspection, mapping, public safety, and emerging commercial work. Paid operations generally require FAA Part 107 certification."],
  ["people", "Flight Instructor", "Teach new pilots, strengthen your own knowledge, and build experience toward advanced professional flying goals."],
  ["globe", "Air Traffic Control", "Direct aircraft safely in the air and on the ground using communication, radar, focus, and rapid decision-making."],
  ["calendar", "Airport Operations", "Keep an airfield safe and efficient through inspections, maintenance coordination, wildlife management, security, and emergency response."],
  ["document", "Flight Dispatch", "Plan and monitor routes, evaluate weather and fuel needs, and coordinate between flight crews and operations teams."],
  ["wrench", "Aircraft Maintenance", "Inspect, troubleshoot, and repair airframes, engines, avionics, and aircraft systems as an A&P mechanic or maintenance specialist."],
  ["code", "Aeronautical Engineering", "Design and improve aircraft, systems, structures, interiors, and technology while balancing safety and performance."],
  ["cloud", "Meteorology", "Forecast the atmospheric conditions that affect every flight and help crews make safe operational decisions."],
  ["people", "Cabin Crew & Customer Experience", "Protect passenger safety and comfort in the cabin and support travelers throughout the airport journey."],
  ["user", "Aerospace Medicine", "Support the health, safety, and performance of people involved in air and space travel."],
  ["document", "Aviation Law & Business", "Work where aviation meets regulation, insurance, airport management, business, policy, and risk."],
  ["plane", "Airline Pilot", "Fly passengers for major or regional airlines while working through structured training, experience, and FAA certification requirements."],
  ["plane", "Corporate, Charter & Air Taxi Pilot", "Fly people and business aircraft on flexible missions for companies, private owners, and charter operators."],
  ["plane", "Cargo & Ferry Pilot", "Move packages or deliver aircraft between owners, operators, maintenance facilities, and destinations around the world."],
  ["plane", "Medical & Air Ambulance Pilot", "Support urgent medical transport, patient transfers, organ delivery, and other time-critical healthcare missions."],
  ["plane", "Government, Military & Law Enforcement Pilot", "Fly airplanes, helicopters, or uncrewed aircraft in public service, national defense, emergency response, and law enforcement."],
  ["plane", "Firefighting & Agricultural Pilot", "Use specialized aircraft at low altitude to fight wildfires, protect crops, and support land-management missions."],
  ["plane", "Air Tour, Media & Banner Pilot", "Fly sightseeing, news, patrol, photography, and aerial advertising missions that require precision and strong local knowledge."],
  ["plane", "Test, Airshow & Space Pilot", "Evaluate new aircraft, demonstrate advanced flying, compete in aerobatics, or help shape future commercial spaceflight."],
  ["people", "Airport Customer Service", "Guide travelers from check-in through boarding, solve problems, and support safe, welcoming airport operations."],
  ["people", "Airport Emergency Response", "Respond to aircraft incidents, medical emergencies, fires, alarms, and other hazards across an airport campus."],
  ["people", "Airport Police & Security", "Protect airport facilities and travelers through patrol, investigation, traffic control, security, and emergency response."],
  ["wrench", "Avionics Technician", "Install, inspect, troubleshoot, and repair the electronic instruments, communications, navigation, and control systems inside aircraft."],
  ["people", "Aviation Training & Education", "Design curricula and teach pilots, mechanics, controllers, and other aviation professionals in schools and training centers."],
  ["document", "Aviation Insurance & Risk", "Help aircraft owners, operators, manufacturers, and insurers understand coverage, claims, liability, and operational risk."],
  ["document", "Airport Engineering & Construction", "Plan, design, build, and maintain runways, terminals, utilities, and other critical airport infrastructure."],
  ["spacecraft", "Space Science & Astronautics", "Study spacecraft, missions, planetary science, space systems, and the environments beyond Earth."],
] as const;

export const scholarships = [
  ["plane", "EAA Ray Aviation Scholarship", "Up to $12,000*", "Ages 16–19 · Chapter nomination"],
  ["plane", "EAA Air Academy Alumni Scholarship", "Varies*", "Initial training · EAA Air Academy alumni"],
  ["people", "Harrison Ford Scholarship", "Varies*", "Young Eagles · Financial need considered"],
  ["path", "Adapt to Fly Scholarship", "Varies*", "Pilots with disabilities · Eligibility applies"],
  ["cap", "Civil Air Patrol Cadet Wings", "Funded training*", "CAP cadets · Private pilot pathway"],
  ["plane", "AOPA Foundation Scholarship", "$2,500+*", "Age 16+ · Student pilot certificate"],
  ["school", "AOPA High School Flight Training", "Up to $10,000*", "Ages 16–18 · GPA and test requirements"],
  ["people", "LeRoy W. Homer Jr. Scholarship", "Training support*", "Ages 16–23 · Private pilot training"],
  ["people", "The Ninety-Nines First Wings", "Up to $6,000*", "Student pilot members · Milestone based"],
  ["people", "Amelia Earhart Memorial Scholarship", "Up to $20,000*", "The Ninety-Nines members · Advanced training"],
  ["globe", "SSA Discover Soaring Scholarship", "Training awards*", "Young non-pilots · Glider training"],
  ["plane", "Dennis Purduski Flight Training Scholarship", "Up to $2,000*", "SSA members ages 13–19 · Pre-solo"],
  ["plane", "WSPA Sky Ghost Scholarship", "Up to $1,500*", "Women under 25 · Glider certificate"],
  ["school", "EAA Post-Secondary Scholarship", "Varies*", "Aviation degree or technical education"],
  ["school", "SSA Kolstad Award", "Up to $10,000*", "Ages 14–25 · College study"],
  ["school", "Astronaut Scholarship", "Up to $15,000*", "College juniors/seniors · STEM research"],
  ["plane", "John S. Bradbury Memorial Scholarship", "Varies*", "EAA Young Eagles · Flight training"],
  ["plane", "Noah Favaregh Flight Training Scholarship", "Varies*", "Post-solo students · Financial need"],
  ["plane", "Jason Kurt Lohr Aviation Scholarship", "Varies*", "Ages 18–23 · Post-solo fixed-wing training"],
  ["people", "Elgin Wells Jr. Starjammer CFI Scholarship", "Varies*", "Future long-term flight instructors"],
  ["people", "Florence Coffy Gregory Scholarship", "Varies*", "Young women · Flight training"],
  ["people", "EAA WomenSoar Scholarship", "Varies*", "Women age 17+ · Certificates and ratings"],
  ["school", "AOPA Teacher Flight Training Scholarship", "Up to $12,000*", "Teachers using AOPA aviation STEM curriculum"],
  ["plane", "Top Gun Naval Aviator Scholarship", "Varies*", "Advanced rating · Aspiring professional or naval pilots"],
  ["people", "Ceci Stratford Flight Training Scholarship", "Varies*", "Women age 16+ · Primary or advanced training"],
  ["people", "Ninety-Nines Flight Training Scholarship", "Up to $20,000*", "Members · Advanced certificates and ratings"],
  ["school", "Ninety-Nines Academic Scholarship", "Up to $10,000*", "Members · Aviation or aerospace degree"],
  ["wrench", "Ninety-Nines Technical Training Scholarship", "Up to $20,000*", "Members · Aviation technical certification"],
  ["plane", "Vicki Cruse Memorial Scholarship", "Training award*", "Members · Emergency maneuver and aerobatic training"],
  ["people", "Kitty Houghton Memorial Scholarship", "Varies*", "Women pilots in emerging-economy countries"],
  ["people", "Women in Aviation International Scholarships", "Varies*", "WAI members · Multiple aviation pathways"],
  ["plane", "Sling Pilot Academy Scholarship", "Up to $20,000*", "Accelerated professional flight training"],
  ["plane", "Alaska Airlines Flight Training Scholarship", "Up to $14,000*", "Washington high-school students age 16+"],
  ["plane", "Benjamin L. Ellison Future Pilot Scholarship", "Up to $14,000*", "Youth · Solo and private pilot pathway"],
  ["plane", "Frank Sam and Betty Houston Scholarship", "Up to $14,000*", "Washington high-school students age 16+"],
  ["plane", "Red-Tailed Hawks FLY Program", "Funded training*", "Ages 16–21 · Ground school, flight training, mentoring"],
  ["globe", "SSA Stoffel Flight Training Scholarship", "Up to $2,000*", "SSA members ages 13–25 · Glider training"],
  ["globe", "1-26 Association Scholarship", "Up to $1,000*", "Student glider pilots under 18"],
  ["globe", "WSPA Mid Kolstad Scholarship", "Up to $1,500*", "Women over 25 · Glider certificate or add-on"],
  ["school", "Edward B. Shafer Future of Flight Scholarship", "Up to $5,000*", "College students · Aviation careers"],
  ["school", "NBAA Charities Scholarships", "Varies*", "Business aviation education and professional development"],
  ["school", "Navigate Your Future Scholarship", "Up to $2,500*", "High-school graduates · Aviation study"],
  ["school", "GAMA Scholarships", "Varies*", "Aviation-related college and training programs"],
  ["school", "Air & Space Forces Association Scholarships", "Varies*", "Airmen, Guardians, families, and educators"],
] as const;

export const organizations = [
  ["Experimental Aircraft Association & Young Eagles", "Free introductory Young Eagles flights for ages 8–17, aviation education, ground-school benefits, events, scholarships, and a worldwide recreational aviation community.", ["Youth flights", "Education", "Scholarships"]],
  ["Aircraft Owners and Pilots Association", "Flight-training materials, safety education, scholarships, flying clubs, advocacy, and a large network for general aviation pilots and students.", ["Training", "Safety", "Community"]],
  ["Civil Air Patrol", "Aerospace education, leadership development, community service, emergency services, and flight opportunities through its cadet program.", ["Cadets", "Leadership", "Flight training"]],
  ["Junior ROTC", "A high-school leadership and citizenship program that can provide aerospace education, service experience, and exposure to aviation careers.", ["High school", "Leadership", "Service"]],
  ["Aviation Career Education Academy", "Hands-on workshops, field trips, mentorship, and flight experiences that introduce students to aviation and aerospace careers.", ["Hands-on", "Mentorship", "Careers"]],
  ["Academy of Model Aeronautics", "Model aviation training, safety education, events, competitions, and a welcoming entry point into flight for learners of all ages.", ["Model aircraft", "STEM", "Events"]],
  ["Red-Tailed Hawks Flying Club", "A Seattle-based community expanding aviation access through mentorship, workshops, flight experiences, and the FLY training program.", ["Community", "Mentorship", "Youth"]],
  ["Women in Aviation International", "Scholarships, conferences, mentoring, education, and a global network supporting women across aviation and aerospace.", ["Women", "Scholarships", "Network"]],
  ["The Ninety-Nines", "An international community of women pilots offering scholarships, mentorship, education, and support from first flight through advanced ratings.", ["Women pilots", "Mentorship", "Scholarships"]],
  ["Organization of Black Aerospace Professionals", "Networking, mentorship, education, and career development focused on increasing Black representation in aviation and aerospace.", ["Diversity", "Careers", "Mentorship"]],
  ["Soaring Society of America", "Training resources, local club connections, competitions, workshops, safety education, and scholarships for glider pilots.", ["Gliders", "Training", "Scholarships"]],
  ["Women's Soaring Pilots Association", "Mentorship, fly-ins, workshops, community, and scholarships that support women learning and advancing in soaring.", ["Women", "Gliders", "Community"]],
  ["National Business Aviation Association", "Scholarships, career resources, safety education, professional development, and connections across the business aviation community.", ["Business aviation", "Careers", "Scholarships"]],
  ["General Aviation Manufacturers Association", "Education, workforce development, scholarships, and industry information connecting students to aircraft manufacturing and technology.", ["Manufacturing", "Engineering", "Scholarships"]],
  ["Air & Space Forces Association", "STEM education, scholarships, educator support, and programs serving Airmen, Guardians, their families, and future aerospace leaders.", ["Aerospace", "STEM", "Scholarships"]],
  ["NASA STEM Gateway", "Challenges, internships, learning experiences, educator resources, and pathways that connect students with NASA missions and careers.", ["Space", "STEM", "Internships"]],
  ["National Air Transportation Association", "Career resources, scholarships, safety programs, and industry connections across aviation businesses and airport services.", ["Aviation business", "Careers", "Scholarships"]],
] as const;

export const manuscriptResources = [
  ["document", "Pilot Certificate Guide", "Understand Student, Private, Commercial, CFI, CFII, ATP, Sport, and Recreational pilot certificates, and what each one lets you do.", "Explore Certificates"],
  ["plane", "Scholarship Application Toolkit", "Start early, check eligibility first, track every deadline, save reusable answers, and tell a clear story about your goals.", "Find Funding"],
  ["people", "Mentors & Aviation Networks", "Learn how local clubs, flight schools, aviation events, and national organizations can help open doors.", "Meet the Community"],
  ["school", "College & Training Pathways", "Compare Part 141 flight programs, aviation degrees, aerospace engineering programs, and technical education.", "Explore Education"],
  ["path", "Nine Tips for Getting Started", "Research, find mentors, set milestones, seek funding, stay resilient, gain experience, train early, follow industry changes, and embrace curiosity.", "Read the Tips"],
  ["headphones", "Ishitha’s Journey", "From a Young Eagles flight at 14 to glider solo, pilot certificates, scholarships, and a mission to make aviation easier to enter.", "Discover the Story"],
] as const;

export function slugify(value: string) {
  return value.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
