export type DetailInfo = {
  officialUrl: string;
  sourceLabel: string;
  overview: string;
  highlights: string[];
  nextSteps: string[];
};

export const organizationDetails: Record<string, DetailInfo> = {
  "experimental-aircraft-association-and-young-eagles": {
    officialUrl: "https://www.eaa.org/eaa/youth/free-ye-flights",
    sourceLabel: "EAA Young Eagles",
    overview: "EAA’s Young Eagles program introduces young people ages 8–17 to personal aviation through free flights with volunteer EAA pilots. After a flight, students can unlock additional learning and membership benefits.",
    highlights: ["Free introductory flights for ages 8–17", "Free student membership after a Young Eagles flight", "Online ground-school and aviation-learning benefits", "Local chapters, mentors, events, and scholarship pathways"],
    nextSteps: ["Find a nearby Young Eagles flight", "Meet your local EAA chapter", "Ask about youth programs and scholarships"],
  },
  "aircraft-owners-and-pilots-association": {
    officialUrl: "https://www.aopa.org/",
    sourceLabel: "AOPA",
    overview: "AOPA supports general aviation pilots and learners through safety education, flight-training resources, advocacy, events, flying-club information, and scholarships.",
    highlights: ["Flight-training and student resources", "Free safety courses and seminars", "AOPA Foundation scholarships", "Flying clubs and aviation community"],
    nextSteps: ["Explore AOPA’s student resources", "Review the current scholarship cycle", "Use safety courses as you begin training"],
  },
  "civil-air-patrol": {
    officialUrl: "https://www.gocivilairpatrol.com/programs/cadets",
    sourceLabel: "Civil Air Patrol",
    overview: "Civil Air Patrol’s cadet program combines aerospace education, leadership, physical fitness, character development, service, and access to aviation experiences.",
    highlights: ["Aerospace education and orientation flights", "Leadership progression and community service", "Local squadrons across the United States", "Cadet Wings and other flight-training opportunities"],
    nextSteps: ["Find a local squadron", "Attend a prospective-member meeting", "Ask about orientation flights and Cadet Wings"],
  },
  "junior-rotc": {
    officialUrl: "https://www.airuniversity.af.edu/Holm-Center/AFJROTC/",
    sourceLabel: "Air Force Junior ROTC",
    overview: "Junior ROTC programs help high-school students develop leadership, citizenship, discipline, teamwork, and—in many units—exposure to aerospace education and aviation careers.",
    highlights: ["School-based leadership development", "Community service and team activities", "Aerospace and aviation exposure in participating programs", "No requirement to enter military service"],
    nextSteps: ["Ask whether your school offers JROTC", "Review the program’s activities and expectations", "Look for aviation or flight-focused opportunities"],
  },
  "aviation-career-education-academy": {
    officialUrl: "https://www.faa.gov/education/ace_academy",
    sourceLabel: "FAA ACE Academies",
    overview: "FAA Aviation Career Education Academies introduce students to aviation careers through age-appropriate programs that may include airport visits, hands-on learning, speakers, and flight experiences.",
    highlights: ["Career exploration for students", "Hands-on aviation and STEM learning", "Programs hosted in different regions", "Exposure to pilots, engineers, airports, and aviation systems"],
    nextSteps: ["Check the FAA’s current academy listings", "Review age and location requirements", "Apply to a program near you"],
  },
  "academy-of-model-aeronautics": {
    officialUrl: "https://www.modelaircraft.org/",
    sourceLabel: "Academy of Model Aeronautics",
    overview: "The Academy of Model Aeronautics connects people through model aviation and provides education, safety guidance, clubs, competitions, and a practical introduction to aerodynamics and flight.",
    highlights: ["Local model-aircraft clubs", "STEM and youth education", "Safety guidance and flying resources", "Competitions, events, and community"],
    nextSteps: ["Find a local AMA club", "Visit a flying event", "Start with a beginner-friendly model or simulator"],
  },
  "red-tailed-hawks-flying-club": {
    officialUrl: "https://www.redtailedhawks.org/",
    sourceLabel: "Red-Tailed Hawks Flying Club",
    overview: "Red-Tailed Hawks Flying Club expands access to aviation through youth education, mentorship, community activities, and hands-on flight opportunities, with roots in the Seattle area.",
    highlights: ["Youth aviation outreach", "Mentoring and role models", "Hands-on learning and flight experiences", "A focus on access and representation"],
    nextSteps: ["Review current youth programs", "Attend a community event", "Ask about mentoring or flight-training opportunities"],
  },
  "women-in-aviation-international": {
    officialUrl: "https://www.wai.org/",
    sourceLabel: "Women in Aviation International",
    overview: "Women in Aviation International supports people across aviation and aerospace with chapters, conferences, scholarships, education, networking, and career development.",
    highlights: ["Local and collegiate chapters", "Annual scholarships", "Mentoring and professional networking", "Girls in Aviation Day and youth outreach"],
    nextSteps: ["Find a local chapter", "Review scholarship opportunities", "Attend an event or Girls in Aviation Day"],
  },
  "the-ninety-nines": {
    officialUrl: "https://www.ninety-nines.org/",
    sourceLabel: "The Ninety-Nines",
    overview: "The Ninety-Nines is an international organization of women pilots offering community, mentoring, scholarships, education, and support from a first certificate through advanced aviation careers.",
    highlights: ["International network of women pilots", "First Wings and Amelia Earhart Memorial awards", "Local chapters and mentoring", "Education and aviation outreach"],
    nextSteps: ["Explore student pilot membership", "Find a nearby chapter", "Review current scholarship requirements"],
  },
  "organization-of-black-aerospace-professionals": {
    officialUrl: "https://obap.org/",
    sourceLabel: "OBAP",
    overview: "OBAP works to inspire and support underrepresented people in aerospace through education, mentoring, professional development, scholarships, and exposure to aviation careers.",
    highlights: ["Youth aerospace education", "Mentoring and career development", "Industry networking", "Programs that strengthen representation"],
    nextSteps: ["Explore current student programs", "Review upcoming events", "Connect with mentors and the OBAP community"],
  },
  "soaring-society-of-america": {
    officialUrl: "https://www.ssa.org/",
    sourceLabel: "Soaring Society of America",
    overview: "SSA supports soaring in the United States with local club connections, safety information, training resources, competitions, youth programs, and glider scholarships.",
    highlights: ["Find soaring clubs and commercial operators", "Youth and junior scholarships", "Safety, training, and educational resources", "Competitions and a national soaring community"],
    nextSteps: ["Find a gliderport or soaring club", "Arrange an introductory flight", "Review junior scholarships"],
  },
  "womens-soaring-pilots-association": {
    officialUrl: "https://womensoaring.org/",
    sourceLabel: "Women’s Soaring Pilots Association",
    overview: "WSPA promotes soaring for women through scholarships, mentoring, seminars, fly-ins, education, and an international community of glider pilots.",
    highlights: ["Beginner and advanced soaring scholarships", "Mentors for scholarship recipients", "Annual Women’s Soaring Seminar", "Community for women glider pilots"],
    nextSteps: ["Review WSPA membership", "Explore the current scholarships", "Attend a seminar or connect with a mentor"],
  },
};

const eaaScholarships = "https://www.eaa.org/eaa/learn-to-fly/scholarships";
const aopaScholarships = "https://www.aopa.org/training-and-safety/students/aopa-flight-training-scholarships";
const ninetyNinesScholarships = "https://www.ninety-nines.org/scholarships.htm";
const ssaScholarships = "https://www.ssa.org/soaring-scholarships/";

export const scholarshipDetails: Record<string, DetailInfo> = {
  "eaa-ray-aviation-scholarship": { officialUrl:"https://www.eaa.org/eaa/eaa-chapters/eaa-chapter-resources/chapter-programs-and-activities/ray-aviation-scholarship-fund", sourceLabel:"EAA", overview:"The Ray Aviation Scholarship is a merit-based flight-training program funded by the Ray Foundation, managed by EAA, and administered through local EAA chapters. Candidates work through a participating chapter rather than applying directly to the national program.", highlights:["Up to $12,000 toward flight training","Local EAA chapter nomination and mentoring","Designed for highly engaged young aviators","Training milestones and chapter participation"], nextSteps:["Find and participate in a local EAA chapter","Ask the chapter scholarship coordinator about nominations","Prepare to explain your goals, commitment, and training plan"] },
  "eaa-air-academy-alumni-scholarship": { officialUrl:eaaScholarships, sourceLabel:"EAA Scholarships", overview:"This EAA scholarship supports eligible Air Academy alumni pursuing initial flight training. Current availability and requirements are listed in EAA’s active scholarship application.", highlights:["Connection to EAA Air Academy participation","Support for an initial certificate or solo milestone","Part of EAA’s broader scholarship program"], nextSteps:["Review EAA’s current scholarship list","Confirm Air Academy eligibility","Prepare one strong EAA scholarship application"] },
  "harrison-ford-scholarship": { officialUrl:eaaScholarships, sourceLabel:"EAA Scholarships", overview:"An EAA scholarship associated with supporting Young Eagles as they pursue flight training, aviation education, or technical pathways. Availability and criteria may vary by cycle.", highlights:["Young Eagles connection","Aviation training or education focus","Financial need may be considered"], nextSteps:["Review the current EAA scholarship cycle","Document your Young Eagles and chapter involvement","Explain how the award advances your aviation goal"] },
  "adapt-to-fly-scholarship": { officialUrl:eaaScholarships, sourceLabel:"EAA Scholarships", overview:"Adapt to Fly was created to expand aviation access for people with disabilities who can meet the applicable operational and medical eligibility requirements.", highlights:["Disability-focused aviation access","Training toward an eligible pilot certificate","Individual aircraft-control and medical requirements apply"], nextSteps:["Review current EAA availability","Discuss medical eligibility with qualified professionals","Identify an accessible training environment"] },
  "civil-air-patrol-cadet-wings": { officialUrl:"https://www.gocivilairpatrol.com/programs/cadets/cadetinvest/cadet-wings", sourceLabel:"Civil Air Patrol", overview:"Cadet Wings is Civil Air Patrol’s merit-based pathway helping qualified cadets progress toward a Private Pilot Certificate through approved training and structured support.", highlights:["For eligible Civil Air Patrol cadets","Structured private-pilot training pathway","Training may occur locally or through approved providers","Commitment and cadet performance matter"], nextSteps:["Join and actively participate in CAP","Review current Cadet Wings prerequisites","Build a strong record in leadership and aerospace activities"] },
  "aopa-foundation-scholarship": { officialUrl:aopaScholarships, sourceLabel:"AOPA Foundation", overview:"AOPA Foundation scholarships support eligible members pursuing primary flight training, advanced certificates and ratings, aviation maintenance, and other aviation career pathways.", highlights:["Multiple awards through one current program","AOPA membership and residency requirements apply","Primary and advanced training pathways","Application cycles and award amounts change"], nextSteps:["Join or verify AOPA membership","Review the active application window","Prepare essays, references, and a practical training plan"] },
  "aopa-high-school-flight-training": { officialUrl:aopaScholarships, sourceLabel:"AOPA Foundation", overview:"AOPA periodically offers flight-training awards directed toward high-school students. The current AOPA Foundation page is the authoritative place to confirm which student awards are active.", highlights:["High-school student focus","Private pilot training pathway","Academic and knowledge-test criteria may apply","Current cycle determines available awards"], nextSteps:["Review current AOPA scholarship listings","Confirm age, membership, and academic criteria","Plan for the FAA knowledge test if required"] },
  "leroy-w-homer-jr-scholarship": { officialUrl:"https://leroywhomerjr.org/scholarships/", sourceLabel:"The LeRoy W. Homer Jr. Foundation", overview:"The foundation supports dedicated young people pursuing a Private Pilot Certificate independently rather than as part of a college aviation degree program.", highlights:["Private pilot training focus","Youth eligibility requirements","Independent flight-training pathway","Annual application window"], nextSteps:["Review the foundation’s current criteria","Identify a flight school and realistic budget","Prepare a compelling application about your aviation commitment"] },
  "the-ninety-nines-first-wings": { officialUrl:ninetyNinesScholarships, sourceLabel:"The Ninety-Nines", overview:"First Wings provides milestone-based assistance to eligible Student Pilot members of The Ninety-Nines who are working toward their first pilot certificate.", highlights:["Up to $6,000 through training milestones","Student Pilot membership period required","Recent logged flight time required","Applications are typically offered twice yearly"], nextSteps:["Review Student Pilot membership","Track flight time and training milestones","Confirm the next official deadline"] },
  "amelia-earhart-memorial-scholarship": { officialUrl:ninetyNinesScholarships, sourceLabel:"The Ninety-Nines", overview:"The Amelia Earhart Memorial Scholarship Fund supports qualified Ninety-Nines members pursuing advanced flight training, academic study, technical training, research, and specialized aviation goals.", highlights:["Advanced flight-training awards","Academic and technical pathways","Membership and rating requirements vary","Annual application through the members area"], nextSteps:["Review the scholarship categories","Confirm membership-duration requirements","Choose the category that directly matches your next milestone"] },
  "ssa-discover-soaring-scholarship": { officialUrl:"https://www.ssa.org/discover-scholarship/", sourceLabel:"Soaring Society of America", overview:"Discover Soaring introduces young non-pilots to gliding through training credits and other awards sponsored through a participating U.S. soaring organization.", highlights:["For young non-pilots","Glider training credits","A sponsoring soaring organization is important","Interest, financial need, and promise are considered"], nextSteps:["Visit a gliderport","Find a sponsoring club or commercial operator","Explain why soaring fits your goals"] },
  "dennis-purduski-flight-training-scholarship": { officialUrl:"https://www.ssa.org/dennis-purduski-flight-training-scholarship/", sourceLabel:"Soaring Society of America", overview:"This SSA scholarship supports pre-solo youth members with direct glider flight-training expenses and emphasizes commitment, a clear plan, community involvement, and mentoring.", highlights:["Ages 13–19 and pre-solo","Up to $2,000 in flight-training support","SSA membership required","Personal statement and recommendations"], nextSteps:["Join SSA and a local soaring community","Define specific training goals","Ask mentors for recommendations early"] },
  "wspa-sky-ghost-scholarship": { officialUrl:"https://womensoaring.org/scholarships/", sourceLabel:"Women’s Soaring Pilots Association", overview:"The Sky Ghost Scholarship supports a young woman pursuing glider training toward a private certificate. Membership, age, flight experience, and current-cycle requirements apply.", highlights:["For young women glider pilots","WSPA membership required","Training toward a Private Glider Certificate","Mentoring accompanies WSPA’s scholarship community"], nextSteps:["Review the current WSPA scholarship guide","Confirm WSPA and SSA membership requirements","Prepare your training record and aviation goals"] },
  "eaa-post-secondary-scholarship": { officialUrl:eaaScholarships, sourceLabel:"EAA Scholarships", overview:"EAA post-secondary scholarships support aviation-related college and technical study, including engineering, maintenance, air traffic control, aviation business, professional flight, and related STEM fields.", highlights:["College and technical education","Many aviation fields can qualify","Current and incoming students may apply","One EAA process may match multiple awards"], nextSteps:["Confirm your program is aviation related","Review EAA’s current application dates","Show how your education leads to active aviation involvement"] },
  "ssa-kolstad-award": { officialUrl:ssaScholarships, sourceLabel:"Soaring Society of America", overview:"The Kolstad Award supports college-level academic study for accomplished young soaring pilots who demonstrate achievement, service, and strong educational and career goals.", highlights:["Up to $10,000 toward academic study","Competitive award for ages 14–25","Soaring achievement and service matter","Funds are paid toward education"], nextSteps:["Review current SSA requirements","Document soaring achievement and service","Request detailed recommendations"] },
  "astronaut-scholarship": { officialUrl:"https://www.astronautscholarship.org/programs/astronaut-scholarship/", sourceLabel:"Astronaut Scholarship Foundation", overview:"The Astronaut Scholarship Foundation supports exceptional U.S. undergraduate STEM students who show significant research, creativity, leadership, and potential to advance science and technology. Students must be nominated by a participating university.", highlights:["Up to $15,000","For eligible juniors and seniors in STEM","Faculty nomination through a participating university","Includes mentoring, networking, and professional development"], nextSteps:["Confirm that your university participates","Speak with faculty or the university liaison","Build a strong record of research and work beyond the classroom"] },
};

export const careerDetails: Record<string, DetailInfo> = {
  "professional-pilot-careers": { officialUrl:"https://www.bls.gov/ooh/transportation-and-material-moving/airline-and-commercial-pilots.htm", sourceLabel:"U.S. Bureau of Labor Statistics", overview:"Professional pilots fly and navigate airplanes, helicopters, and other aircraft in airline, charter, cargo, corporate, public-service, instructional, and specialized operations.", highlights:["Preflight planning and aircraft inspection","Weather, navigation, communication, and decision-making","FAA certificates, ratings, medical qualification, and experience","Schedules and training vary widely by employer"], nextSteps:["Take a discovery flight","Learn the Student and Private Pilot certificate pathway","Compare local flight schools and aviation colleges"] },
  "drone-pilot": { officialUrl:"https://www.faa.gov/newsroom/small-unmanned-aircraft-systems-uas-regulations-part-107", sourceLabel:"Federal Aviation Administration", overview:"Drone pilots use small uncrewed aircraft in photography, mapping, inspection, agriculture, public safety, research, and other commercial or government work.", highlights:["Commercial operations generally fall under FAA Part 107","Remote pilots must understand airspace and operating rules","A remote pilot certificate requires an FAA knowledge pathway","Technology and use cases continue to expand"], nextSteps:["Learn recreational drone safety first","Study current Part 107 rules","Practice flight planning, weather, and airspace awareness"] },
  "flight-instructor": { officialUrl:"https://www.faa.gov/pilots/become", sourceLabel:"Federal Aviation Administration", overview:"Certified Flight Instructors teach knowledge, procedures, decision-making, and aircraft control while helping students prepare for solos, certificates, ratings, and flight reviews.", highlights:["Requires advanced pilot knowledge and instructional skill","Builds communication, leadership, and judgment","Can help pilots accumulate professional experience","Different instructor ratings cover airplanes and instruments"], nextSteps:["Begin with a Private Pilot Certificate","Progress through instrument and commercial training","Observe and learn from effective instructors"] },
  "air-traffic-control": { officialUrl:"https://www.faa.gov/jobs/career_fields/aviation_careers", sourceLabel:"Federal Aviation Administration", overview:"Air traffic controllers coordinate aircraft movements to maintain safe separation and efficient traffic flow in airport towers, approach facilities, and en-route centers.", highlights:["Fast, precise communication","Strong focus and situational awareness","Specialized FAA hiring and training process","Shift work and high responsibility"], nextSteps:["Review current FAA hiring requirements","Build math, communication, and decision-making skills","Learn how the national airspace system works"] },
  "airport-operations": { officialUrl:"https://www.faa.gov/airports", sourceLabel:"Federal Aviation Administration", overview:"Airport operations teams help keep airfields safe, secure, compliant, and ready for daily traffic and emergencies.", highlights:["Airfield inspections and condition reporting","Wildlife, snow, construction, and maintenance coordination","Emergency and security response","Coordination with airlines, tenants, and air traffic control"], nextSteps:["Tour or volunteer at a local airport","Study airport management and safety","Look for airport internships or entry-level roles"] },
  "flight-dispatch": { officialUrl:"https://www.faa.gov/pilots/training/atp", sourceLabel:"Federal Aviation Administration", overview:"Aircraft dispatchers work with flight crews and operations teams to plan safe flights, evaluate weather and routes, calculate fuel, monitor changes, and support operational decisions.", highlights:["Weather and route analysis","Fuel and performance planning","Operational communication and monitoring","FAA certification applies to airline dispatchers"], nextSteps:["Learn weather and flight planning fundamentals","Explore FAA-approved dispatcher programs","Build calm communication and analytical skills"] },
  "aircraft-maintenance": { officialUrl:"https://www.bls.gov/ooh/installation-maintenance-and-repair/aircraft-and-avionics-equipment-mechanics-and-technicians.htm", sourceLabel:"U.S. Bureau of Labor Statistics", overview:"Aircraft and avionics technicians inspect, maintain, repair, and troubleshoot aircraft structures, engines, electrical systems, instruments, and electronic equipment.", highlights:["Safety-critical hands-on work","Airframe, powerplant, and avionics specializations","Technical-school and supervised-experience pathways","FAA mechanic certification may be required"], nextSteps:["Visit an aviation maintenance program","Build mechanical and electrical skills","Learn about FAA A&P certification pathways"] },
  "aeronautical-engineering": { officialUrl:"https://www.bls.gov/ooh/architecture-and-engineering/aerospace-engineers.htm", sourceLabel:"U.S. Bureau of Labor Statistics", overview:"Aerospace engineers design, analyze, test, and improve aircraft, spacecraft, propulsion, structures, controls, and related systems.", highlights:["Mathematics, physics, design, and computing","Testing, simulation, and systems thinking","Usually requires an engineering degree","Work spans industry, research, defense, and government"], nextSteps:["Strengthen math, physics, and coding","Join engineering or model-aircraft projects","Compare accredited aerospace and mechanical engineering programs"] },
  "meteorology": { officialUrl:"https://www.bls.gov/ooh/life-physical-and-social-science/atmospheric-scientists-including-meteorologists.htm", sourceLabel:"U.S. Bureau of Labor Statistics", overview:"Meteorologists analyze the atmosphere and forecast conditions that directly influence routing, safety, performance, and operational decisions in aviation.", highlights:["Weather observation and forecasting","Data, models, radar, and satellite analysis","Science degree commonly required","Aviation forecasting requires operational awareness"], nextSteps:["Study earth science, physics, and mathematics","Learn to read aviation weather products","Explore atmospheric-science degree programs"] },
  "cabin-crew-and-customer-experience": { officialUrl:"https://www.bls.gov/ooh/transportation-and-material-moving/flight-attendants.htm", sourceLabel:"U.S. Bureau of Labor Statistics", overview:"Flight attendants and customer-service teams protect safety, support passengers, respond to emergencies, and help the travel system operate smoothly.", highlights:["Passenger and cabin safety","Emergency procedures and first aid","Clear communication and service","Schedules may include nights, weekends, and travel"], nextSteps:["Build customer-service experience","Practice communication and teamwork","Review airline hiring and training expectations"] },
  "aerospace-medicine": { officialUrl:"https://www.faa.gov/pilots/medical_certification", sourceLabel:"Federal Aviation Administration", overview:"Aerospace medicine focuses on the health, safety, and performance of people in aviation and space environments, including medical certification, human factors, and aeromedical care.", highlights:["Medicine connected to flight and space environments","Pilot medical certification and safety","Human performance and physiology","Requires professional medical education for physician roles"], nextSteps:["Explore medicine, biology, and human factors","Learn what Aviation Medical Examiners do","Seek mentors in aerospace medicine"] },
  "aviation-law-and-business": { officialUrl:"https://www.faa.gov/about/office_org/headquarters_offices/agc", sourceLabel:"Federal Aviation Administration", overview:"Aviation law and business cover regulation, certification, insurance, airport and airline management, finance, policy, contracts, accident claims, and risk.", highlights:["Strong writing, research, analysis, and negotiation","Work across private companies and government","Legal careers require law school and licensing","Business roles span airlines, airports, and manufacturers"], nextSteps:["Explore aviation business or policy courses","Follow FAA regulatory topics","Seek internships at airports, airlines, law firms, or aviation organizations"] },
};
