export const organizationLogos: Record<string, string[]> = {
  "Experimental Aircraft Association & Young Eagles": ["/organization-logos/eaa.png", "/organization-logos/young-eagles.png"],
  "Aircraft Owners and Pilots Association": ["/scholarship-logos/aopa.svg"],
  "Civil Air Patrol": ["/organization-logos/civil-air-patrol.png"],
  "Junior ROTC": ["/organization-logos/afjrotc.svg"],
  "Aviation Career Education Academy": ["/organization-logos/faa.svg"],
  "Academy of Model Aeronautics": ["/organization-logos/ama.svg"],
  "Red-Tailed Hawks Flying Club": ["/scholarship-logos/red-tailed-hawks.svg"],
  "Women in Aviation International": ["/organization-logos/women-in-aviation.png"],
  "The Ninety-Nines": ["/scholarship-logos/ninety-nines.svg"],
  "Organization of Black Aerospace Professionals": ["/organization-logos/obap.png"],
  "Soaring Society of America": ["/scholarship-logos/ssa.svg"],
  "Women's Soaring Pilots Association": ["/organization-logos/wspa-official-upload.svg"],
  "National Business Aviation Association": ["/scholarship-logos/nbaa.svg"],
  "General Aviation Manufacturers Association": ["/scholarship-logos/gama.svg"],
  "Air & Space Forces Association": ["/scholarship-logos/afa.svg"],
  "NASA STEM Gateway": ["/organization-logos/nasa.svg"],
  "National Air Transportation Association": ["/organization-logos/nata.svg"],
};

export const sourceLogo: Record<string, string> = {
  EAA: "/organization-logos/eaa.png",
  "EAA Scholarships": "/organization-logos/eaa.png",
  "EAA Young Eagles": "/organization-logos/young-eagles.png",
  AOPA: "/scholarship-logos/aopa.svg",
  "AOPA Foundation": "/scholarship-logos/aopa.svg",
  "Civil Air Patrol": "/organization-logos/civil-air-patrol.png",
  "Women in Aviation International": "/organization-logos/women-in-aviation.png",
  "Women’s Soaring Pilots Association": "/organization-logos/wspa-official-upload.svg",
  "Women's Soaring Pilots Association": "/organization-logos/wspa-official-upload.svg",
  "The Ninety-Nines": "/scholarship-logos/ninety-nines.svg",
  "Soaring Society of America": "/scholarship-logos/ssa.svg",
  "1-26 Association": "/scholarship-logos/ssa.svg",
  OBAP: "/organization-logos/obap.png",
  "Red-Tailed Hawks Flying Club": "/scholarship-logos/red-tailed-hawks.svg",
  "The Museum of Flight": "/scholarship-logos/museum-of-flight.svg",
  "Academy of Model Aeronautics": "/organization-logos/ama.svg",
  "Air Force Junior ROTC": "/organization-logos/afjrotc.svg",
  "FAA ACE Academies": "/organization-logos/faa.svg",
  "The LeRoy W. Homer Jr. Foundation": "/scholarship-logos/leroy-homer.svg",
  "Astronaut Scholarship Foundation": "/scholarship-logos/asf.svg",
  "Sling Pilot Academy": "/scholarship-logos/sling.svg",
  "NBAA Charities": "/scholarship-logos/nbaa.svg",
  NBAA: "/scholarship-logos/nbaa.svg",
  GAMA: "/scholarship-logos/gama.svg",
  "Air & Space Forces Association": "/scholarship-logos/afa.svg",
  "National Air Transportation Foundation": "/organization-logos/nata.svg",
  NATA: "/organization-logos/nata.svg",
  NASA: "/organization-logos/nasa.svg",
  "NASA STEM Gateway": "/organization-logos/nasa.svg",
};
