import Link from "next/link";
import { PageShell } from "../ui";

export default function BookPage() {
  return <PageShell active="about">
    <section className="book-page-hero">
      <img className="actual-book-cover" src="/cleared-for-takeoff-cover.png" alt="Cleared for Takeoff book cover by Ishitha Arekapudi"/>
      <div><span className="eyebrow">THE BOOK BEHIND SKY RIDERS GATEWAY</span><h1>Cleared for Takeoff</h1><p className="book-deck">A practical roadmap for young people ready to explore aviation and aerospace, even when the first step is not obvious.</p><a className="primary-button" href="#purchase">Buy From Sky Riders →</a></div>
    </section>
    <section className="section book-excerpt"><span className="eyebrow">FROM THE PREFACE</span><h2>The journey begins here.</h2><div className="excerpt-copy"><p>Imagine looking up in 2037 and seeing a sky filled with airplanes, piloted by a new generation of aviators and knowing that somewhere beyond Earth’s atmosphere, humans are living and working on Mars. This vision is no longer science fiction. Aviation and space are transforming in ways once unimaginable.</p><p>These trends reveal a unique opportunity for today’s young people: the chance to lead in fields that are reshaping the future of our world and beyond. Today’s teens and young adults will be the next explorers, the pioneers who will push past Earth’s borders and redefine what’s possible. This generation, our generation, has the chance to mark milestones in human history.</p><p>I wrote <i>Cleared for Takeoff</i> as a guide to help you navigate the paths to becoming pilots, engineers, scientists, mechanics, and innovators, empowering you to explore careers in aviation and space. While opportunities in these fields are expanding, they can often seem out of reach. My goal with this book is to break down those barriers and show you how to access the knowledge, resources, and networks that will open doors and launch your journey.</p><p>It’s never too early to start. From wherever you are right now, there are steps you can take to begin building your path, whether that’s learning about aviation basics, joining a STEM program, or finding a mentor. Consider this book your roadmap, a way to help you find direction, gain confidence, and explore all the opportunities that aviation and space have to offer.</p><p>The future of aviation and space is waiting, and it’s calling for people like you to answer. I invite you to take on this challenge, to dream big, and to be part of humanity’s next great venture. Together, let’s clear the way for takeoff.</p></div><p className="excerpt-credit">From the preface of <i>Cleared for Takeoff</i> by Ishitha Arekapudi.</p></section>
    <section className="section book-purchase" id="purchase"><div><span className="eyebrow">ORDER DIRECTLY</span><h2>Bring the roadmap with you.</h2><p>Online checkout is being prepared. This space is ready for direct book purchases once payment and shipping are connected.</p></div><div className="purchase-panel"><strong>Cleared for Takeoff</strong><span>Print edition</span><button disabled>Checkout Coming Soon</button><Link href="/account">Create an account for launch updates →</Link></div></section>
  </PageShell>;
}
