export type VerifiedLocation = {
  id: string; organization_slug: string; organization_name: string; location_name: string;
  location_type: "flight_school" | "squadron" | "chapter" | "program" | "official_finder";
  city: string; state: string; postal_code: string; latitude: number; longitude: number;
  official_url: string; source_url: string; description: string;
};

// Public organization locations verified against official program pages.
export const verifiedLocations: VerifiedLocation[] = [
  { id:"ca-scfc", organization_slug:"san-carlos-flight-center", organization_name:"San Carlos Flight Center", location_name:"San Carlos Flight Center", location_type:"flight_school", city:"San Carlos", state:"California", postal_code:"94070", latitude:37.5119, longitude:-122.2495, official_url:"https://sancarlosflight.com/", source_url:"https://sancarlosflight.com/", description:"Flight training, discovery flights, safety seminars, and an aviation community at San Carlos Airport." },
  { id:"ca-cap-west-bay", organization_slug:"civil-air-patrol", organization_name:"Civil Air Patrol", location_name:"West Bay Composite Squadron 192", location_type:"squadron", city:"San Carlos", state:"California", postal_code:"94070", latitude:37.5117, longitude:-122.2497, official_url:"https://www.gocivilairpatrol.com/cap-unit-locator", source_url:"https://www.gocivilairpatrol.com/cap-unit-locator", description:"A Civil Air Patrol squadron serving cadets and adult members in the Peninsula area." },
  { id:"ca-cap-east-bay", organization_slug:"civil-air-patrol", organization_name:"Civil Air Patrol", location_name:"East Bay Cadet Squadron 18", location_type:"squadron", city:"Hayward", state:"California", postal_code:"94545", latitude:37.6589, longitude:-122.1215, official_url:"https://www.gocivilairpatrol.com/cap-unit-locator", source_url:"https://www.gocivilairpatrol.com/cap-unit-locator", description:"A cadet squadron offering aerospace education, leadership, fitness, and service experiences." },
  { id:"ca-eaa-20", organization_slug:"experimental-aircraft-association", organization_name:"Experimental Aircraft Association", location_name:"EAA Chapter 20 Young Eagles", location_type:"chapter", city:"San Carlos", state:"California", postal_code:"94070", latitude:37.5119, longitude:-122.2495, official_url:"https://chapters.eaa.org/eaa20", source_url:"https://www.eaa.org/eaa/eaa-chapters/chaptergram-articles/2024-08-20-2024-young-eagles-volunteer-awards", description:"Local EAA chapter with Young Eagles activities and free introductory flights for eligible youth." },
  { id:"ca-hiller", organization_slug:"hiller-aviation-museum", organization_name:"Hiller Aviation Museum", location_name:"Hiller Aviation Museum Programs", location_type:"program", city:"San Carlos", state:"California", postal_code:"94070", latitude:37.5129, longitude:-122.2504, official_url:"https://www.hiller.org/", source_url:"https://www.hiller.org/", description:"Hands-on aviation and STEM exhibits, camps, workshops, and youth learning experiences." },
  { id:"ca-advantage", organization_slug:"advantage-aviation", organization_name:"Advantage Aviation", location_name:"Advantage Aviation", location_type:"flight_school", city:"Palo Alto", state:"California", postal_code:"94303", latitude:37.4543, longitude:-122.1101, official_url:"https://www.advantage-aviation.com/", source_url:"https://www.advantage-aviation.com/", description:"Flight instruction and aircraft access at Palo Alto Airport for new and continuing pilots." },
  { id:"ca-wvfc-pao", organization_slug:"west-valley-flying-club", organization_name:"West Valley Flying Club", location_name:"West Valley Flying Club, Palo Alto", location_type:"flight_school", city:"Palo Alto", state:"California", postal_code:"94303", latitude:37.4530, longitude:-122.1111, official_url:"https://www.wvfc.org/", source_url:"https://www.wvfc.org/", description:"Flight training and a community flying club with a Palo Alto Airport location." },
  { id:"ca-eaa-119", organization_slug:"experimental-aircraft-association", organization_name:"Experimental Aircraft Association", location_name:"EAA Chapter 119 Young Eagles", location_type:"chapter", city:"Watsonville", state:"California", postal_code:"95076", latitude:36.9357, longitude:-121.7895, official_url:"https://chapters.eaa.org/eaa119", source_url:"https://chapters.eaa.org/eaa119/about-us", description:"Watsonville-area chapter offering Young Eagles rallies and aviation education activities." },
  { id:"ca-eaa-14", organization_slug:"experimental-aircraft-association", organization_name:"Experimental Aircraft Association", location_name:"EAA Chapter 14 Young Eagles", location_type:"chapter", city:"San Diego", state:"California", postal_code:"92154", latitude:32.5723, longitude:-116.9802, official_url:"https://chapters.eaa.org/eaa14/young-eagles", source_url:"https://chapters.eaa.org/eaa14/young-eagles", description:"Monthly Young Eagles rallies at Brown Field introduce youth ages 8–17 to general aviation." },
  { id:"ca-eaa-1", organization_slug:"experimental-aircraft-association", organization_name:"Experimental Aircraft Association", location_name:"EAA Chapter 1 Young Eagles", location_type:"chapter", city:"Riverside", state:"California", postal_code:"92509", latitude:33.9887, longitude:-117.4105, official_url:"https://chapters.eaa.org/eaa1", source_url:"https://chapters.eaa.org/eaa1/about-us", description:"EAA Chapter One offers Young Eagles, seminars, workshops, and aviation community programs." },
];
